version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:


services:
  db_foodgram:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: alinemr/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/media/
    depends_on:
      - db_foodgram

  frontend:
    image: alinemr/foodgram_frontend  
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: alinemr/foodgram_gateway  
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media:/media/
    ports:
      - 10000:80