version: '3.3'
volumes:
  pg_data:
  static:
  media:
services:
  db_foodgram:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/media/
    depends_on:
      - db_foodgram
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - static:/static
      - media:/media/