version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:


services:
  db_foodgram:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: alinemr/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/media/
    depends_on:
      - db_foodgram

  frontend:
    image: alinemr/foodgram_frontend  
    env_file: .env
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  gateway:
    image: alinemr/foodgram_gateway  
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/sites-enabled/default
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/staticfiles/
      - media:/media/
    ports:
      - 10000:80