# Generated by Django 3.2 on 2023-10-04 13:08

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_user', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', error_messages={'unique': 'Тег с таким цветом уже существует!'}, image_field=None, max_length=25, samples=None, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z_]*$', 'Допускаются только заглавные буквы и подчеркивания.')], verbose_name='Цвет(HEX-код)'),
        ),
    ]
