# Generated by Django 3.2 on 2023-09-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_color_tag_colour'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='Нельзя рецепт добавить дважды в список покупок',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_shopping_cart',
        ),
    ]
