# Generated by Django 4.2.4 on 2023-09-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_follow_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='units_of_measurement',
            new_name='measurement_unit',
        ),
    ]
