# Generated by Django 3.2 on 2023-10-02 10:36

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230928_2139'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='Нельзя подписаться дважды!',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='colour',
            new_name='color',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, author=django.db.models.expressions.F('user')), name='Нельзя подписаться на самого себя!'),
        ),
    ]
