# Generated by Django 3.2 on 2023-10-03 12:34

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20231002_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', error_messages={'unique': 'Тег с таким цветом уже существует!'}, image_field=None, max_length=25, samples=None, unique=True, verbose_name='Цвет(HEX-код)'),
        ),
        migrations.AddConstraint(
            model_name='ingredientrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_combination'),
        ),
    ]
