# Generated by Django 3.2 on 2023-10-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_ingredientrecipe_unique_recipe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientrecipe',
            name='unique_recipe',
        ),
    ]
